run:
output:
linters-settings:
  govet:
    enable-all: true
linters:
  enable:
    - govet
  presets:
    - bugs
    - comment
    - complexity
    - import
    - performance
    - unused
  issues:
  severity:
