// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddSongs: typeof import('./src/components/addSongs.vue')['default']
    Album: typeof import('./src/components/album.vue')['default']
    AlbumArt: typeof import('./src/components/albumArt.vue')['default']
    DatabaseInfo: typeof import('./src/components/databaseInfo.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    DownloadCover: typeof import('./src/components/downloadCover.vue')['default']
    Folder: typeof import('./src/components/folder.vue')['default']
    Folders: typeof import('./src/components/folders.vue')['default']
    FontAwesomeIcon: typeof import('@fortawesome/vue-fontawesome')['FontAwesomeIcon']
    LikeSong: typeof import('./src/components/likeSong.vue')['default']
    Listbox: typeof import('@headlessui/vue')['Listbox']
    ListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    ListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    ListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    MediaController: typeof import('./src/components/mediaController.vue')['default']
    Outputs: typeof import('./src/components/outputs.vue')['default']
    PlaybackCommands: typeof import('./src/components/playbackCommands.vue')['default']
    PlaybackOptions: typeof import('./src/components/playbackOptions.vue')['default']
    Playlist: typeof import('./src/components/playlist.vue')['default']
    PlaylistMenu: typeof import('./src/components/playlistMenu.vue')['default']
    ProgressBar: typeof import('./src/components/progressBar.vue')['default']
    QueueMenu: typeof import('./src/components/queueMenu.vue')['default']
    QueuePagination: typeof import('./src/components/queuePagination.vue')['default']
    RadioGroup: typeof import('@headlessui/vue')['RadioGroup']
    RadioGroupLabel: typeof import('@headlessui/vue')['RadioGroupLabel']
    RadioGroupOption: typeof import('@headlessui/vue')['RadioGroupOption']
    RenamePlaylist: typeof import('./src/components/renamePlaylist.vue')['default']
    SaveQueue: typeof import('./src/components/saveQueue.vue')['default']
    Search: typeof import('./src/components/search.vue')['default']
    Setting: typeof import('./src/components/setting.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    SidebarButton: typeof import('./src/components/sidebarButton.vue')['default']
    SongInfo: typeof import('./src/components/songInfo.vue')['default']
    StoredPlaylist: typeof import('./src/components/storedPlaylist.vue')['default']
    Switch: typeof import('@headlessui/vue')['Switch']
    SwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    SwitchLabel: typeof import('@headlessui/vue')['SwitchLabel']
    Tab: typeof import('@headlessui/vue')['Tab']
    TabGroup: typeof import('@headlessui/vue')['TabGroup']
    TabList: typeof import('@headlessui/vue')['TabList']
    TabPanel: typeof import('@headlessui/vue')['TabPanel']
    TabPanels: typeof import('@headlessui/vue')['TabPanels']
    TextInput: typeof import('./src/components/textInput.vue')['default']
    ThemeSettings: typeof import('./src/components/themeSettings.vue')['default']
    VolumeControl: typeof import('./src/components/volumeControl.vue')['default']
  }
}
